version: '3.8'

services:
  web:
    build:
      context: ./core
      dockerfile: Dockerfile
    container_name: social_auth_web
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./core/.env
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    container_name: social_auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./core/.env.db
  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: